#!/bin/bash

# This script is intended to execute a 'run' script located in the current
# directory. It searches for '.uai' files in the working directory, including
# all of its subdirectories. The 'run' script is then executed for each '.uai'
# file found.

# https://superuser.com/questions/461946/can-i-use-pipe-output-as-a-shell-script-argument

# Check if any arguments were provided
if [ $# -ne 0 ]; then
  echo "Usage: $0"
  exit 1
fi

# Execute the 'run_mmap' script for each '.uai' file
fd -e .uai . | xargs -I {} ./run_mmap {}
